alias: MQTT Ping Pong
description: >-
  Triggers a notification and publishes an MQTT message upon receiving a
  specific MQTT message.
trigger:
  - platform: mqtt
    topic: testIn
    payload: Ping
condition: []
action:
  - service: notify.notify
    data:
      message: Triggered
  - service: mqtt.publish
    data:
      topic: testOut
      payload: Pong
mode: queued
max: 10
