alias: Timed State Publish
description: Publish the state of an entity on regular time intervals
trigger:
  - platform: time_pattern
    seconds: /10
condition: []
action:
  - service: mqtt.publish
    data:
      topic: testOut
      payload_template: '{{states(''sensor.router_sent_packets'')}}'
mode: single